package auth_handlers

const (
	AUTH_STATE_VERIFICATION_MAIL_SENT       string = "VERIFICATION_MAIL_SENT"
	AUTH_STATE_VERIFICATION_MAIL_NOT_SENT   string = "VERIFICATION_MAIL_NOT_SENT"
	AUTH_STATE_USER_REGISTRATION_COMPLETE   string = "USER_REGISTRATION_COMPLETE"
	AUTH_STATE_USER_REGISTRATION_INCOMPLETE string = "USER_REGISTRATION_INCOMPLETE"
)
