name: Check, Lint & Format Code
env:
  PNPM_STORE_PATH: ''
on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: true
        description: Node Version
      pnpm-version:
        type: number
        required: true
        description: PNPM Version
      timeout-minutes:
        type: number
        default: 5
        required: false
        description: Timeout in minutes

jobs:
  check-lint-format:
    name: Typecheck, Lint and Format
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version  }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        run: pnpm install
      - name: Check Types
        run: pnpm check
      - name: Check Linting
        run: pnpm lint
      - name: Check Formatting
        run: pnpm format
