name: CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - apps/web/**
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  ci:
    uses: './.github/workflows/check-lint-format.yml'
    with:
      node-version: 22
      pnpm-version: 8.15.6
