name: CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - apps/web/**
      - packages/**

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}-${{ github.event.pull_request.number}}

jobs:
  ci:
    uses: './.github/workflows/check-lint-format.yml'
    with:
      node-version: 22
